language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo test --all --verbose
  - rustup component add clippy rustfmt &&
    cargo clippy &&
    cargo fmt -- --check
